# Generated by Django 4.2.5 on 2023-09-13 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crime',
            old_name='occurence',
            new_name='occur',
        ),
    ]
